### ISSUE TITLE
Note: "Parallel Burst FFT" might not be running in parallel

### ISSUE THREAD

**Issue by johannesvollmer** [keijiro/FourierTransform#1]
I've had a look at the code trying to use it.

Then I noticed that the jobs should not be able to run in parallel. The following code (simplified):

```c#
var handle = new FirstPassJob(...)
for(...)
    handle = new DftPassJob { ... }.Schedule(..., handle);
```

As you can see, a bunch of jobs are created, which I assume should be run in parallel. However, each of the parallel jobs depends on the job handle of the previous loop iteration, which means all the jobs will be executed in sequence, and not in parallel. Is it correct?

**Comment by keijiro** [comment]
Yes and no. Some parts of the algorithm run in parallel. Specifically saying, we only can parallelize the DFT part of the algorithm. Other parts run in sequence.

![FFT](https://upload.wikimedia.org/wikipedia/commons/c/cb/DIT-FFT-butterfly.png)
